on: [push]
jobs:
  lint:
    runs-on: docker
    steps:
      - uses: https://github.com/cachix/install-nix-action@v31
      - name: Setup Attic
        run: |
          nix profile add "nixpkgs#attic-client"
          attic login main https://attic.kybe.xyz/main ${{ secrets.ATTIC_KEY }}
          attic use main
      - name: Build & Checks
        run: |
          nix build git+https://git.kybe.xyz/2kybe3/kystash --max-jobs 32 -L
          nix flake check git+https://git.kybe.xyz/2kybe3/kystash --max-jobs 32 -L
      - name: Push to Attic
        if: always()
        run: attic push main $(ls -d /nix/store/*/)
